### ISSUE TITLE
Annoying white background on deploy screen

### ISSUE THREAD

**Issue by rpgadea** [nickc01/Obsidian#2]
When u select deploy in a web proyect, the background is all white.
Can u change it to the original black?

**Comment by nickc01** [comment]
I"ll see if I can find a fix for this when I have time

**Comment by nickc01** [comment]
Sorry for the long wait, but I wasn't able to find the specific property that determined the color for the web project background. So what I ended up doing was completely rebuilding the theme from scratch based on the latest version of the Visual Studio Dark Theme and that seemed to have fixed the problem. I'll be pushing the new changes soon:
![Before Update](https://user-images.githubusercontent.com/12601671/168397736-1710415b-5b06-4cf8-8b54-cf3efe008578.PNG)

![After Update](https://user-images.githubusercontent.com/12601671/168397745-646f01bb-ee25-40d5-9cb1-b2e00db5aca5.PNG)

**Comment by rpgadea** [comment]
Thanks a lot man for your time.
