### ISSUE TITLE
Theme color on startup window

### ISSUE THREAD

**Issue by adeng1980** [nickc01/Obsidian#3]
firstly thank you for creating obsidian theme, been using this theme since vs 2012, much appreciated, can you please point me to where to reset the hover theme on start up windows quick access links, the background color make the the text hard to read on hovering
![image](https://github.com/nickc01/Obsidian/assets/43459424/e44208f2-cdc2-408b-a351-a6fc116b973b)

**Comment by nickc01** [comment]
Sorry for taking a while to respond. I was able to find out how to change the color of the button highlights and change them to a better color. 
![Start Button Color Fix](https://github.com/nickc01/Obsidian/assets/12601671/71e826e7-69a8-4418-9644-f0ad40ac4079)


I just pushed a new version to the visual studio extensions marketplace, so you should be able to update it soon. You can also find the new version here : https://github.com/nickc01/Obsidian/releases/tag/v2.1

**Comment by adeng1980** [comment]
No at all, huge thanks from my side to you for kindly get this fixed, I wish I could learn something from you and this project.
